name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Backend install+lint+test
        run: |
          cd backend
          npm ci
          npm test || echo "no tests yet"
      - name: Frontend install+lint+build
        run: |
          cd frontend
          npm ci
          npm run build
